In [3]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv('/Users/sa12/Documents/Repositories/MusicReccomendation/MusicRecommendation/Data/train.csv')
hc_labels = pd.read_csv('/Users/sa12/Documents/Repositories/MusicReccomendation/MusicRecommendation/Data/HC_labels.csv')

In [12]:
#create df for desired output.
data['labels'] = hc_labels['labels']
data = data[['artist_name', 'track_name','genre','labels']]
data

                artist_name                     track_name    genre  labels
0                    mukesh           mohabbat bhi jhoothi      pop       4
1             frankie laine                      i believe      pop       8
2               johnnie ray                            cry      pop       2
3               pérez prado                       patricia      pop       4
4      giorgos papadopoulos             apopse eida oneiro      pop       8
...                     ...                            ...      ...     ...
28357               mack 10                10 million ways  hip hop       9
28358                m.o.p.  ante up (robbin hoodz theory)  hip hop       9
28359                  nine                  whutcha want?  hip hop       9
28360            will smith                         switch  hip hop       9
28361                 jeezy                         r.i.p.  hip hop       9

[28362 rows x 4 columns]

In [53]:
#choose a cluster 0-9
sample = data[data['labels'] == 7]
#how many recommendations to provide
sample.sample(5)

         artist_name           track_name    genre  labels
14515        santana          brotherhood    blues       7
20564      tesseract           tourniquet     jazz       7
6594   one direction              history      pop       7
4835        no doubt  simple kind of life      pop       7
11171  rascal flatts  waiting all my life  country       7